"""Constants for LADX state extraction."""

MAX_ENTITIES = 0x10
INVENTORY_SLOT_COUNT = 0x0C

ENTITY_STATUS_NAMES = {
    0: "ENTITY_STATUS_DISABLED",
    1: "ENTITY_STATUS_DYING",
    2: "ENTITY_STATUS_FALLING",
    3: "ENTITY_STATUS_BURNING",
    4: "ENTITY_STATUS_INIT",
    5: "ENTITY_STATUS_ACTIVE",
    6: "ENTITY_STATUS_STUNNED",
    7: "ENTITY_STATUS_LIFTED",
    8: "ENTITY_STATUS_THROWN",
}

