NewStaffRoles::
    db "    1998 TEAM     "
    db "    SUPERVISOR    "
    db "      REGIE       "
    db "     DREHBUCH     "
    db "  PROGRAMMIERUNG  "
    db "      DESIGN      "
    db "      MUSIK       "
    db "     ARTWORK      "
    db "  TECHN.BERATUNG  "
    db "  DEUTSCHER TEXT  "
    db "BESONDEREN DANK AN"
    db "    MONITORING    "
    db "    1993 TEAM     "
    db "  DUNGEON DESIGN  "
    db "  ILLUSTRATIONEN  "
    db "PRODUKTIONSLEITUNG"
    db "    PRODUKTION    "
    db "                  "

NewStaffPeople::
    db "                  "
    db "  TAKASHI TEZUKA  "
    db "YOSINORI TUTIYAMA "
    db "  NOBUO MATSUMIYA "
    db "    EIJI NOTO     "
    db "   KIYOSHI KODA   "
    db "SIGEHIRO KASAMATU "
    db "  MIKIO MISHIMA   "
    db "   KYOKO KIMURA   "
    db "   YUICHI OZAKI   "
    db "   KEIKO IZAWA    "
    db "   N KOGANEZAWA   "
    db "  CLAUDE M[ MOYSE "
    db "   THOMAS RINKE   "
    db "   CLUB NINTENDO  "
    db "  AKIYA SAKAMOTO  "
    db " HIROKO ISHIKAWA  "
    db " SUPER MARIO CLUB "
    db "YASUHISA YAMAMURA "
    db "  KENSUKE TANABE  "
    db " YOSHIAKI KOIZUMI "
    db "  KAZUAKI MORITA  "
    db "TAKAMITSU KUZUHARA"
    db " MASANAO ARIMOTO  "
    db "  SHIGEFUMI HINO  "
    db "  KAZUMI TOTAKA   "
    db "  MINAKO HAMANO   "
    db "  KOZUE ISHIKAWA  "
    db "  YOUICHI KOTABE  "
    db "  CLAUDE M[ MOYSE "
    db " TOSHIHIKO NAKAGO "
    db "    KOJI KONDO    "
    db " TOMOAKI KUROUME  "
    db " YOSHIYUKI ONISHI "
    db "      NOE PT      "
    db " SHIGERU MIYAMOTO "
    db " HIROSHI YAMAUCHI "
    db "  ", $5C, $5D, $5E, $5F, "            "
