NewStaffRoles::
    db "    1998 STAFF    "
    db "   SUPERVISEUR    "
    db "   REALISATEUR    "
    db "    SCENARISTE    "
    db "   PROGRAMMEUR    "
    db "   INFOGRAPHIE    "
    db "  MONTAGE SONORE  "
    db "     ART WORK     "
    db "SUPPORT TECHNIQUE "
    db " TEXTES FRANCAIS  "
    db " REMERCIEMENTS A  "
    db "   DEBUG STAFF    "
    db "    1993 STAFF    "
    db "CONCEPTEUR DONJONS"
    db "   ILLUSTRATEUR   "
    db "    PRODUCTEUR    "
    db "PRODUCTEUR DELEGUE"
    db "                  "

NewStaffPeople::
    db "                  "
    db "  TAKASHI TEZUKA  "
    db "YOSINORI TUTIYAMA "
    db "  NOBUO MATSUMIYA "
    db "    EIJI NOTO     "
    db "   KIYOSHI KODA   "
    db "SIGEHIRO KASAMATU "
    db "  MIKIO MISHIMA   "
    db "   KYOKO KIMURA   "
    db "   YUICHI OZAKI   "
    db "   KEIKO IZAWA    "
    db "   N KOGANEZAWA   "
    db " JULIEN BARDAKOFF "
    db "  AKIYA SAKAMOTO  "
    db " HIROKO ISHIKAWA  "
    db " HIROYUKI UESUGI  "
    db " SUPER MARIO CLUB "
    db "      NOE PT      "
    db "YASUHISA YAMAMURA "
    db "  KENSUKE TANABE  "
    db " YOSHIAKI KOIZUMI "
    db "  KAZUAKI MORITA  "
    db "TAKAMITSU KUZUHARA"
    db " MASANAO ARIMOTO  "
    db "  SHIGEFUMI HINO  "
    db "  KAZUMI TOTAKA   "
    db "  MINAKO HAMANO   "
    db "  KOZUE ISHIKAWA  "
    db "  YOUICHI KOTABE  "
    db "VERONIQUE CHANTEL "
    db " TOSHIHIKO NAKAGO "
    db "    KOJI KONDO    "
    db " TOMOAKI KUROUME  "
    db " KENJI HARAGUCHI  "
    db "                  "
    db " SHIGERU MIYAMOTO "
    db " HIROSHI YAMAUCHI "
    db "  [\\]^            "


DebugStaffRoles::

OriginalStaffRoles::
