; File generated automatically by `tools/generate_map_data.py`

; Values for hAnimatedTilesGroup
DEF ANIMATED_TILES_NONE           EQU $00
DEF ANIMATED_TILES_COUNTER        EQU $01
DEF ANIMATED_TILES_TIDE           EQU $02
DEF ANIMATED_TILES_VILLAGE        EQU $03
DEF ANIMATED_TILES_DUNGEON_1      EQU $04
DEF ANIMATED_TILES_UNDERGROUND    EQU $05
DEF ANIMATED_TILES_LAVA           EQU $06
DEF ANIMATED_TILES_DUNGEON_2      EQU $07
DEF ANIMATED_TILES_WARP_TILE      EQU $08
DEF ANIMATED_TILES_CURRENTS       EQU $09
DEF ANIMATED_TILES_WATERFALL      EQU $0A
DEF ANIMATED_TILES_WATERFALL_SLOW EQU $0B
DEF ANIMATED_TILES_WATER_DUNGEON  EQU $0C
DEF ANIMATED_TILES_LIGHT_BEAM     EQU $0D
DEF ANIMATED_TILES_CRYSTAL_BLOCK  EQU $0E
DEF ANIMATED_TILES_BUBBLES        EQU $0F
DEF ANIMATED_TILES_WEATHER_VANE   EQU $10
DEF ANIMATED_TILES_PHOTO          EQU $11
