; File generated automatically by `tools/generate_map_data.py`

; Values for hAnimatedTilesGroup
ANIMATED_TILES_NONE           equ $00
ANIMATED_TILES_COUNTER        equ $01
ANIMATED_TILES_TIDE           equ $02
ANIMATED_TILES_VILLAGE        equ $03
ANIMATED_TILES_DUNGEON_1      equ $04
ANIMATED_TILES_UNDERGROUND    equ $05
ANIMATED_TILES_LAVA           equ $06
ANIMATED_TILES_DUNGEON_2      equ $07
ANIMATED_TILES_WARP_TILE      equ $08
ANIMATED_TILES_CURRENTS       equ $09
ANIMATED_TILES_WATERFALL      equ $0A
ANIMATED_TILES_WATERFALL_SLOW equ $0B
ANIMATED_TILES_WATER_DUNGEON  equ $0C
ANIMATED_TILES_LIGHT_BEAM     equ $0D
ANIMATED_TILES_CRYSTAL_BLOCK  equ $0E
ANIMATED_TILES_BUBBLES        equ $0F
ANIMATED_TILES_WEATHER_VANE   equ $10
ANIMATED_TILES_PHOTO          equ $11
