include "constants/debug.asm"
include "constants/labels.asm"
include "constants/gameplay.asm"
include "constants/gbhw.asm"
include "constants/hram.asm"
include "constants/gfx.asm"
include "constants/vram.asm"
include "constants/wram.asm"
