; Constants for dialog IDs

;DIALOG_                                                equ $000
DIALOG_MARIN_LINK_WAKES_UP                              equ $001
;DIALOG_                                                equ $002
;DIALOG_                                                equ $003
;DIALOG_                                                equ $004
;DIALOG_                                                equ $005
;DIALOG_                                                equ $006
;DIALOG_                                                equ $007
;DIALOG_                                                equ $008
;DIALOG_                                                equ $009
;DIALOG_                                                equ $00A
;DIALOG_                                                equ $00B
;DIALOG_                                                equ $00C
;DIALOG_                                                equ $00D
;DIALOG_                                                equ $00E
;DIALOG_                                                equ $00F
;DIALOG_                                                equ $010
;DIALOG_                                                equ $011
;DIALOG_                                                equ $012
;DIALOG_                                                equ $013
;DIALOG_                                                equ $014
;DIALOG_                                                equ $015
;DIALOG_                                                equ $016
;DIALOG_                                                equ $017
;DIALOG_                                                equ $018
;DIALOG_                                                equ $019
;DIALOG_                                                equ $01A
;DIALOG_                                                equ $01B
;DIALOG_                                                equ $01C
;DIALOG_                                                equ $01D
;DIALOG_                                                equ $01E
;DIALOG_                                                equ $01F
;DIALOG_                                                equ $020
;DIALOG_                                                equ $021
;DIALOG_                                                equ $022
;DIALOG_                                                equ $023
;DIALOG_                                                equ $024
;DIALOG_                                                equ $025
;DIALOG_                                                equ $026
;DIALOG_                                                equ $027
;DIALOG_                                                equ $028
;DIALOG_                                                equ $029
;DIALOG_                                                equ $02A
;DIALOG_                                                equ $02B
;DIALOG_                                                equ $02C
;DIALOG_                                                equ $02D
;DIALOG_                                                equ $02E
;DIALOG_                                                equ $02F
;DIALOG_                                                equ $030
;DIALOG_                                                equ $031
;DIALOG_                                                equ $032
;DIALOG_                                                equ $033
;DIALOG_                                                equ $034
;DIALOG_                                                equ $035
;DIALOG_                                                equ $036
;DIALOG_                                                equ $037
;DIALOG_                                                equ $038
;DIALOG_                                                equ $039
;DIALOG_                                                equ $03A
;DIALOG_                                                equ $03B
;DIALOG_                                                equ $03C
;DIALOG_                                                equ $03D
;DIALOG_                                                equ $03E
;DIALOG_                                                equ $03F
;DIALOG_                                                equ $040
;DIALOG_                                                equ $041
;DIALOG_                                                equ $042
;DIALOG_                                                equ $043
;DIALOG_                                                equ $044
;DIALOG_                                                equ $045
;DIALOG_                                                equ $046
;DIALOG_                                                equ $047
;DIALOG_                                                equ $048
;DIALOG_                                                equ $049
;DIALOG_                                                equ $04A
;DIALOG_                                                equ $04B
;DIALOG_                                                equ $04C
;DIALOG_                                                equ $04D
;DIALOG_                                                equ $04E
;DIALOG_                                                equ $04F
;DIALOG_                                                equ $050
;DIALOG_                                                equ $051
;DIALOG_                                                equ $052
;DIALOG_                                                equ $053
;DIALOG_                                                equ $054
;DIALOG_                                                equ $055
;DIALOG_                                                equ $056
;DIALOG_                                                equ $057
;DIALOG_                                                equ $058
;DIALOG_                                                equ $059
;DIALOG_                                                equ $05A
;DIALOG_                                                equ $05B
;DIALOG_                                                equ $05C
;DIALOG_                                                equ $05D
;DIALOG_                                                equ $05E
;DIALOG_                                                equ $05F
;DIALOG_                                                equ $060
;DIALOG_                                                equ $061
;DIALOG_                                                equ $062
;DIALOG_                                                equ $063
;DIALOG_                                                equ $064
;DIALOG_                                                equ $065
;DIALOG_                                                equ $066
;DIALOG_                                                equ $067
;DIALOG_                                                equ $068
;DIALOG_                                                equ $069
;DIALOG_                                                equ $06A
;DIALOG_                                                equ $06B
;DIALOG_                                                equ $06C
;DIALOG_                                                equ $06D
;DIALOG_                                                equ $06E
;DIALOG_                                                equ $06F
;DIALOG_                                                equ $070
;DIALOG_                                                equ $071
;DIALOG_                                                equ $072
;DIALOG_                                                equ $073
;DIALOG_                                                equ $074
;DIALOG_                                                equ $075
;DIALOG_                                                equ $076
;DIALOG_                                                equ $077
;DIALOG_                                                equ $078
;DIALOG_                                                equ $079
;DIALOG_                                                equ $07A
;DIALOG_                                                equ $07B
;DIALOG_                                                equ $07C
;DIALOG_                                                equ $07D
;DIALOG_                                                equ $07E
;DIALOG_                                                equ $07F
;DIALOG_                                                equ $080
;DIALOG_                                                equ $081
;DIALOG_                                                equ $082
;DIALOG_                                                equ $083
;DIALOG_                                                equ $084
;DIALOG_                                                equ $085
;DIALOG_                                                equ $086
;DIALOG_                                                equ $087
;DIALOG_                                                equ $088
;DIALOG_                                                equ $089
;DIALOG_                                                equ $08A
;DIALOG_                                                equ $08B
;DIALOG_                                                equ $08C
;DIALOG_                                                equ $08D
;DIALOG_                                                equ $08E
;DIALOG_                                                equ $08F
;DIALOG_                                                equ $090
;DIALOG_                                                equ $091
;DIALOG_                                                equ $092
;DIALOG_                                                equ $093
;DIALOG_                                                equ $094
;DIALOG_                                                equ $095
;DIALOG_                                                equ $096
;DIALOG_                                                equ $097
;DIALOG_                                                equ $098
;DIALOG_                                                equ $099
;DIALOG_                                                equ $09A
;DIALOG_                                                equ $09B
;DIALOG_                                                equ $09C
;DIALOG_                                                equ $09D
;DIALOG_                                                equ $09E
;DIALOG_                                                equ $09F
;DIALOG_                                                equ $0A0
;DIALOG_                                                equ $0A1
;DIALOG_                                                equ $0A2
;DIALOG_                                                equ $0A3

; dialog_2.asm starts here
;DIALOG_DialogBirdKeyAcquired                                                equ $0A4
;DIALOG_DialogMapAcquired                                                equ $0A5
;DIALOG_                                                equ $0A6
;DIALOG_                                                equ $0A7
;DIALOG_                                                equ $0A8
;DIALOG_                                                equ $0A9
;DIALOG_                                                equ $0AA
;DIALOG_                                                equ $0AB
;DIALOG_                                                equ $0AC
;DIALOG_                                                equ $0AD
;DIALOG_                                                equ $0AE
;DIALOG_                                                equ $0AF
;DIALOG_                                                equ $0B0
;DIALOG_                                                equ $0B1
;DIALOG_                                                equ $0B2
;DIALOG_                                                equ $0B3
;DIALOG_                                                equ $0B4
;DIALOG_                                                equ $0B5
;DIALOG_                                                equ $0B6
;DIALOG_                                                equ $0B7
;DIALOG_                                                equ $0B8
;DIALOG_                                                equ $0B9
;DIALOG_                                                equ $0BA
;DIALOG_                                                equ $0BB
;DIALOG_                                                equ $0BC
;DIALOG_                                                equ $0BD
;DIALOG_                                                equ $0BE
;DIALOG_                                                equ $0BF
;DIALOG_                                                equ $0C0
;DIALOG_                                                equ $0C1
;DIALOG_                                                equ $0C2
;DIALOG_                                                equ $0C3
;DIALOG_                                                equ $0C4
;DIALOG_                                                equ $0C5
;DIALOG_                                                equ $0C6
;DIALOG_                                                equ $0C7
;DIALOG_                                                equ $0C8
;DIALOG_                                                equ $0C9
;DIALOG_                                                equ $0CA
;DIALOG_                                                equ $0CB
;DIALOG_                                                equ $0CC
;DIALOG_                                                equ $0CD
;DIALOG_                                                equ $0CE
;DIALOG_                                                equ $0CF
;DIALOG_                                                equ $0D0
;DIALOG_                                                equ $0D1
;DIALOG_                                                equ $0D2
;DIALOG_                                                equ $0D3
;DIALOG_                                                equ $0D4
;DIALOG_                                                equ $0D5
;DIALOG_                                                equ $0D6
;DIALOG_                                                equ $0D7
;DIALOG_                                                equ $0D8
;DIALOG_                                                equ $0D9
;DIALOG_                                                equ $0DA
;DIALOG_                                                equ $0DB
;DIALOG_                                                equ $0DC
;DIALOG_                                                equ $0DD
;DIALOG_                                                equ $0DE
;DIALOG_                                                equ $0DF
;DIALOG_                                                equ $0E0
;DIALOG_                                                equ $0E1
;DIALOG_                                                equ $0E2
;DIALOG_                                                equ $0E3
;DIALOG_                                                equ $0E4
;DIALOG_                                                equ $0E5
;DIALOG_                                                equ $0E6
;DIALOG_                                                equ $0E7
;DIALOG_                                                equ $0E8
;DIALOG_                                                equ $0E9
;DIALOG_                                                equ $0EA
;DIALOG_                                                equ $0EB
;DIALOG_                                                equ $0EC
;DIALOG_                                                equ $0ED
;DIALOG_                                                equ $0EE
;DIALOG_                                                equ $0EF
;DIALOG_                                                equ $0F0
;DIALOG_                                                equ $0F1
;DIALOG_                                                equ $0F2
;DIALOG_                                                equ $0F3
;DIALOG_                                                equ $0F4
;DIALOG_                                                equ $0F5
;DIALOG_                                                equ $0F6
;DIALOG_                                                equ $0F7
;DIALOG_                                                equ $0F8
;DIALOG_                                                equ $0F9
;DIALOG_                                                equ $0FA
;DIALOG_                                                equ $0FB
;DIALOG_                                                equ $0FC
;DIALOG_                                                equ $0FD
;DIALOG_                                                equ $0FE
;DIALOG_                                                equ $0FF
;DIALOG_                                                equ $100
;DIALOG_                                                equ $101
;DIALOG_                                                equ $102
;DIALOG_                                                equ $103
;DIALOG_                                                equ $104
;DIALOG_                                                equ $105
;DIALOG_                                                equ $106
;DIALOG_                                                equ $107

; dialog_3.asm starts here
;DIALOG_                                                equ $108
;DIALOG_                                                equ $109
;DIALOG_                                                equ $10A
;DIALOG_                                                equ $10B
;DIALOG_                                                equ $10C
;DIALOG_                                                equ $10D
;DIALOG_                                                equ $10E
;DIALOG_                                                equ $10F
;DIALOG_                                                equ $110
;DIALOG_                                                equ $111
;DIALOG_                                                equ $112
;DIALOG_                                                equ $113
;DIALOG_                                                equ $114
;DIALOG_                                                equ $115
;DIALOG_                                                equ $116
;DIALOG_                                                equ $117
;DIALOG_                                                equ $118
;DIALOG_                                                equ $119
;DIALOG_                                                equ $11A
;DIALOG_                                                equ $11B
;DIALOG_                                                equ $11C
;DIALOG_                                                equ $11D
;DIALOG_                                                equ $11E
;DIALOG_                                                equ $11F
;DIALOG_                                                equ $120
;DIALOG_                                                equ $121
;DIALOG_                                                equ $122
;DIALOG_                                                equ $123
;DIALOG_                                                equ $124
;DIALOG_                                                equ $125
;DIALOG_                                                equ $126
;DIALOG_                                                equ $127
;DIALOG_                                                equ $128
;DIALOG_                                                equ $129
;DIALOG_                                                equ $12A
;DIALOG_                                                equ $12B
;DIALOG_                                                equ $12C
;DIALOG_                                                equ $12D
;DIALOG_                                                equ $12E
;DIALOG_                                                equ $12F
;DIALOG_                                                equ $130
;DIALOG_                                                equ $131
;DIALOG_                                                equ $132
;DIALOG_                                                equ $133
;DIALOG_                                                equ $134
;DIALOG_                                                equ $135
;DIALOG_                                                equ $136
;DIALOG_                                                equ $137
;DIALOG_                                                equ $138
;DIALOG_                                                equ $139
;DIALOG_                                                equ $13A
;DIALOG_                                                equ $13B
;DIALOG_                                                equ $13C
;DIALOG_                                                equ $13D
;DIALOG_                                                equ $13E
;DIALOG_                                                equ $13F
;DIALOG_                                                equ $140
;DIALOG_                                                equ $141
;DIALOG_                                                equ $142
;DIALOG_                                                equ $143
;DIALOG_                                                equ $144
;DIALOG_                                                equ $145
;DIALOG_                                                equ $146
;DIALOG_                                                equ $147
;DIALOG_                                                equ $148
;DIALOG_                                                equ $149
;DIALOG_                                                equ $14A
;DIALOG_                                                equ $14B
;DIALOG_                                                equ $14C
;DIALOG_                                                equ $14D
;DIALOG_                                                equ $14E
;DIALOG_                                                equ $14F
;DIALOG_                                                equ $150
;DIALOG_                                                equ $151
;DIALOG_                                                equ $152
;DIALOG_                                                equ $153
;DIALOG_                                                equ $154
;DIALOG_                                                equ $155
;DIALOG_                                                equ $156
;DIALOG_                                                equ $157
;DIALOG_                                                equ $158
;DIALOG_                                                equ $159
;DIALOG_                                                equ $15A
;DIALOG_                                                equ $15B
;DIALOG_                                                equ $15C
;DIALOG_                                                equ $15D
;DIALOG_                                                equ $15E
;DIALOG_                                                equ $15F
;DIALOG_                                                equ $160
;DIALOG_                                                equ $161
;DIALOG_                                                equ $162
;DIALOG_                                                equ $163
;DIALOG_                                                equ $164
;DIALOG_                                                equ $165
;DIALOG_                                                equ $166
;DIALOG_                                                equ $167
;DIALOG_                                                equ $168
;DIALOG_                                                equ $169
;DIALOG_                                                equ $16A
;DIALOG_                                                equ $16B
;DIALOG_                                                equ $16C
;DIALOG_                                                equ $16D
;DIALOG_                                                equ $16E
;DIALOG_                                                equ $16F
;DIALOG_                                                equ $170
;DIALOG_                                                equ $171
;DIALOG_                                                equ $172
;DIALOG_                                                equ $173
;DIALOG_                                                equ $174
;DIALOG_                                                equ $175
;DIALOG_                                                equ $176
;DIALOG_                                                equ $177
;DIALOG_                                                equ $178
;DIALOG_                                                equ $179
;DIALOG_                                                equ $17A
;DIALOG_                                                equ $17B
;DIALOG_                                                equ $17C
;DIALOG_                                                equ $17D
;DIALOG_                                                equ $17E
;DIALOG_                                                equ $17F
;DIALOG_                                                equ $180
;DIALOG_                                                equ $181
;DIALOG_                                                equ $182
;DIALOG_                                                equ $183
;DIALOG_                                                equ $184
;DIALOG_                                                equ $185
;DIALOG_                                                equ $186
;DIALOG_                                                equ $187
;DIALOG_                                                equ $188
;DIALOG_                                                equ $189
;DIALOG_                                                equ $18A
;DIALOG_                                                equ $18B
;DIALOG_                                                equ $18C
;DIALOG_                                                equ $18D
;DIALOG_                                                equ $18E
;DIALOG_                                                equ $18F

; dialog_4.asm starts here
;DIALOG_                                                equ $190
;DIALOG_                                                equ $191
;DIALOG_                                                equ $192
;DIALOG_                                                equ $193
;DIALOG_                                                equ $194
;DIALOG_                                                equ $195
;DIALOG_                                                equ $196
;DIALOG_                                                equ $197
;DIALOG_                                                equ $198
;DIALOG_                                                equ $199
;DIALOG_                                                equ $19A
;DIALOG_                                                equ $19B
;DIALOG_                                                equ $19C
;DIALOG_                                                equ $19D
;DIALOG_                                                equ $19E
;DIALOG_                                                equ $19F
;DIALOG_                                                equ $1A0
;DIALOG_                                                equ $1A1
;DIALOG_                                                equ $1A2
;DIALOG_                                                equ $1A3
;DIALOG_                                                equ $1A4
;DIALOG_                                                equ $1A5
;DIALOG_                                                equ $1A6
;DIALOG_                                                equ $1A7
;DIALOG_                                                equ $1A8
;DIALOG_                                                equ $1A9
;DIALOG_                                                equ $1AA
;DIALOG_                                                equ $1AB
;DIALOG_                                                equ $1AC
;DIALOG_                                                equ $1AD
;DIALOG_                                                equ $1AE
;DIALOG_                                                equ $1AF
;DIALOG_                                                equ $1B0
;DIALOG_                                                equ $1B1
;DIALOG_                                                equ $1B2
;DIALOG_                                                equ $1B3
;DIALOG_                                                equ $1B4
;DIALOG_                                                equ $1B5
;DIALOG_                                                equ $1B6
;DIALOG_                                                equ $1B7
;DIALOG_                                                equ $1B8
;DIALOG_                                                equ $1B9
;DIALOG_                                                equ $1BA
;DIALOG_                                                equ $1BB
;DIALOG_                                                equ $1BC
;DIALOG_                                                equ $1BD
;DIALOG_                                                equ $1BE
;DIALOG_                                                equ $1BF
;DIALOG_                                                equ $1C0
;DIALOG_                                                equ $1C1
;DIALOG_                                                equ $1C2
;DIALOG_                                                equ $1C3
;DIALOG_                                                equ $1C4
;DIALOG_                                                equ $1C5
;DIALOG_                                                equ $1C6
;DIALOG_                                                equ $1C7
;DIALOG_                                                equ $1C8
DIALOG_DOG_FOOD_DENY                                                equ $1C9
;DIALOG_                                                equ $1CA
;DIALOG_                                                equ $1CB
;DIALOG_                                                equ $1CC
;DIALOG_                                                equ $1CD
;DIALOG_                                                equ $1CE
;DIALOG_                                                equ $1CF
;DIALOG_                                                equ $1D0
;DIALOG_                                                equ $1D1
;DIALOG_                                                equ $1D2
;DIALOG_                                                equ $1D3
;DIALOG_                                                equ $1D4
;DIALOG_                                                equ $1D5
;DIALOG_                                                equ $1D6
;DIALOG_                                                equ $1D7
;DIALOG_                                                equ $1D8
;DIALOG_                                                equ $1D9
;DIALOG_                                                equ $1DA
;DIALOG_                                                equ $1DB
;DIALOG_                                                equ $1DC
;DIALOG_                                                equ $1DD
;DIALOG_                                                equ $1DE
;DIALOG_                                                equ $1DF
;DIALOG_                                                equ $1E0
;DIALOG_                                                equ $1E1
;DIALOG_                                                equ $1E2
;DIALOG_                                                equ $1E3
;DIALOG_                                                equ $1E4
;DIALOG_                                                equ $1E5
;DIALOG_                                                equ $1E6
;DIALOG_                                                equ $1E7
;DIALOG_                                                equ $1E8
;DIALOG_                                                equ $1E9
;DIALOG_                                                equ $1EA
;DIALOG_                                                equ $1EB
;DIALOG_                                                equ $1EC
;DIALOG_                                                equ $1ED
;DIALOG_                                                equ $1EE
;DIALOG_                                                equ $1EF
;DIALOG_                                                equ $1F0
;DIALOG_                                                equ $1F1
;DIALOG_                                                equ $1F2
;DIALOG_                                                equ $1F3
;DIALOG_                                                equ $1F4
;DIALOG_                                                equ $1F5
;DIALOG_                                                equ $1F6
;DIALOG_                                                equ $1F7
;DIALOG_                                                equ $1F8
;DIALOG_                                                equ $1F9
;DIALOG_                                                equ $1FA
;DIALOG_                                                equ $1FB
;DIALOG_                                                equ $1FC
;DIALOG_                                                equ $1FD
;DIALOG_                                                equ $1FE
;DIALOG_                                                equ $1FF
;DIALOG_                                                equ $200
;DIALOG_                                                equ $201
;DIALOG_                                                equ $202
;DIALOG_                                                equ $203
;DIALOG_                                                equ $204
;DIALOG_                                                equ $205
;DIALOG_                                                equ $206
;DIALOG_                                                equ $207
;DIALOG_                                                equ $208
;DIALOG_                                                equ $209
;DIALOG_                                                equ $20A
;DIALOG_                                                equ $20B
;DIALOG_                                                equ $20C
;DIALOG_                                                equ $20D
;DIALOG_                                                equ $20E
;DIALOG_                                                equ $20F
;DIALOG_                                                equ $210
;DIALOG_                                                equ $211
;DIALOG_                                                equ $212
;DIALOG_                                                equ $213
;DIALOG_                                                equ $214
;DIALOG_                                                equ $215
;DIALOG_                                                equ $216
;DIALOG_                                                equ $217
;DIALOG_                                                equ $218
;DIALOG_                                                equ $219
;DIALOG_                                                equ $21A
;DIALOG_                                                equ $21B
;DIALOG_                                                equ $21C
;DIALOG_                                                equ $21D
;DIALOG_                                                equ $21E
;DIALOG_                                                equ $21F
;DIALOG_                                                equ $220
;DIALOG_                                                equ $221
;DIALOG_                                                equ $222
;DIALOG_                                                equ $223
;DIALOG_                                                equ $224
;DIALOG_                                                equ $225
;DIALOG_                                                equ $226
;DIALOG_                                                equ $227
;DIALOG_                                                equ $228
;DIALOG_                                                equ $229
;DIALOG_                                                equ $22A
;DIALOG_                                                equ $22B
;DIALOG_                                                equ $22C
;DIALOG_                                                equ $22D
;DIALOG_                                                equ $22E
;DIALOG_                                                equ $22F
;DIALOG_                                                equ $230
;DIALOG_                                                equ $231
;DIALOG_                                                equ $232
;DIALOG_                                                equ $233
;DIALOG_                                                equ $234
;DIALOG_                                                equ $235
;DIALOG_                                                equ $236
;DIALOG_                                                equ $237
;DIALOG_                                                equ $238
;DIALOG_                                                equ $239
;DIALOG_                                                equ $23A
;DIALOG_                                                equ $23B
;DIALOG_                                                equ $23C
;DIALOG_                                                equ $23D
;DIALOG_                                                equ $23E
;DIALOG_                                                equ $23F
;DIALOG_                                                equ $240
;DIALOG_                                                equ $241
;DIALOG_                                                equ $242
;DIALOG_                                                equ $243
;DIALOG_                                                equ $244
;DIALOG_                                                equ $245
;DIALOG_                                                equ $246
;DIALOG_                                                equ $247
;DIALOG_                                                equ $248
;DIALOG_                                                equ $249
;DIALOG_                                                equ $24A
;DIALOG_                                                equ $24B
;DIALOG_                                                equ $24C
;DIALOG_                                                equ $24D

; dialog_dx.asm starts here
;DIALOG_                                                equ $24E
;DIALOG_                                                equ $24F
;DIALOG_                                                equ $250
;DIALOG_                                                equ $251
;DIALOG_                                                equ $252
;DIALOG_                                                equ $253
;DIALOG_                                                equ $254
;DIALOG_                                                equ $255
;DIALOG_                                                equ $256
;DIALOG_                                                equ $257
;DIALOG_                                                equ $258
;DIALOG_                                                equ $259
;DIALOG_                                                equ $25A
;DIALOG_                                                equ $25B
;DIALOG_                                                equ $25C
;DIALOG_                                                equ $25D
;DIALOG_                                                equ $25E
;DIALOG_                                                equ $25F
;DIALOG_                                                equ $260
;DIALOG_                                                equ $261
;DIALOG_                                                equ $262
;DIALOG_                                                equ $263
;DIALOG_                                                equ $264
;DIALOG_                                                equ $265
;DIALOG_                                                equ $266
;DIALOG_                                                equ $267
;DIALOG_                                                equ $268
;DIALOG_                                                equ $269
;DIALOG_                                                equ $26A
;DIALOG_                                                equ $26B
;DIALOG_                                                equ $26C
;DIALOG_                                                equ $26D
;DIALOG_                                                equ $26E
;DIALOG_                                                equ $26F
;DIALOG_                                                equ $270
;DIALOG_                                                equ $271
;DIALOG_                                                equ $272
;DIALOG_                                                equ $273
;DIALOG_                                                equ $274
;DIALOG_                                                equ $275
;DIALOG_                                                equ $276
;DIALOG_                                                equ $277
;DIALOG_                                                equ $278
;DIALOG_                                                equ $279
;DIALOG_                                                equ $27A
;DIALOG_                                                equ $27B
;DIALOG_                                                equ $27C
;DIALOG_                                                equ $27D
;DIALOG_                                                equ $27E
;DIALOG_                                                equ $27F
;DIALOG_                                                equ $280
;DIALOG_                                                equ $281
;DIALOG_                                                equ $282
;DIALOG_                                                equ $283
;DIALOG_                                                equ $284
;DIALOG_                                                equ $285
;DIALOG_                                                equ $286
;DIALOG_                                                equ $287
;DIALOG_                                                equ $288
;DIALOG_                                                equ $289
;DIALOG_                                                equ $28A
;DIALOG_                                                equ $28B
;DIALOG_                                                equ $28C
;DIALOG_                                                equ $28D
;DIALOG_                                                equ $28E
;DIALOG_                                                equ $28F
;DIALOG_                                                equ $290
;DIALOG_                                                equ $291
;DIALOG_                                                equ $292
;DIALOG_                                                equ $293
;DIALOG_                                                equ $294
;DIALOG_                                                equ $295
;DIALOG_                                                equ $296
;DIALOG_                                                equ $297
;DIALOG_                                                equ $298
;DIALOG_                                                equ $299
;DIALOG_                                                equ $29A
;DIALOG_                                                equ $29B
;DIALOG_                                                equ $29C
;DIALOG_                                                equ $29D
;DIALOG_                                                equ $29E
;DIALOG_                                                equ $29F
;DIALOG_                                                equ $2A0
;DIALOG_                                                equ $2A1
;DIALOG_                                                equ $2A2
;DIALOG_                                                equ $2A3
;DIALOG_                                                equ $2A4
;DIALOG_                                                equ $2A5
;DIALOG_                                                equ $2A6
;DIALOG_                                                equ $2A7
;DIALOG_                                                equ $2A8
;DIALOG_                                                equ $2A9
;DIALOG_                                                equ $2AA
;DIALOG_                                                equ $2AB
;DIALOG_                                                equ $2AC
;DIALOG_                                                equ $2AD
;DIALOG_                                                equ $2AE
;DIALOG_                                                equ $2AF