; Maximum number of loaded entities
def MAX_ENTITIES equ $10

; End marker in a list of entities
def ENTITIES_END equ $FF

; Values for wEntitiesStatusTable
def ENTITY_STATUS_DISABLED   equ 0
def ENTITY_STATUS_DYING      equ 1
def ENTITY_STATUS_FALLING    equ 2
def ENTITY_STATUS_DESTROYING equ 3
def ENTITY_STATUS_INIT       equ 4
def ENTITY_STATUS_ACTIVE     equ 5
def ENTITY_STATUS_STUNNED    equ 6
def ENTITY_STATUS_LIFTED     equ 7
def ENTITY_STATUS_THROWN     equ 8

; Values for wEntitiesOptions1Table
def ENTITY_OPT1_IS_BOSS                equ $80
def ENTITY_OPT1_SWORD_CLINK_OFF        equ $40
def ENTITY_OPT1_ALLOW_OUT_OF_BOUNDS    equ $20
def ENTITY_OPT1_IMMUNE_WATER_PIT       equ $10
def ENTITY_OPT1_SPLASH_IN_WATER        equ $08
def ENTITY_OPT1_IS_MINI_BOSS           equ $04
def ENTITY_OPT1_EXCLUDED_FROM_KILL_ALL equ $02
def ENTITY_OPT1_MOVE_PIT_WATER         equ $01
def ENTITY_OPT1_NONE                   equ $00
; Bit numbers for wEntitiesOptions1Table
def ENTITY_OPT1_B_IS_BOSS                equ 7
def ENTITY_OPT1_B_SWORD_CLINK_OFF        equ 6
def ENTITY_OPT1_B_ALLOW_OUT_OF_BOUNDS    equ 5
def ENTITY_OPT1_B_IMMUNE_WATER_PIT       equ 4
def ENTITY_OPT1_B_SPLASH_IN_WATER        equ 3
def ENTITY_OPT1_B_IS_MINI_BOSS           equ 2
def ENTITY_OPT1_B_EXCLUDED_FROM_KILL_ALL equ 1
def ENTITY_OPT1_B_MOVE_PIT_WATER         equ 0

; Values for wEntitiesPhysicsFlagsTable
def ENTITY_PHYSICS_HARMLESS             equ $80 ; The entity does not damage Link
def ENTITY_PHYSICS_PROJECTILE_NOCLIP    equ $40 ; Projectiles pass through the entity
def ENTITY_PHYSICS_GRABBABLE            equ $20 ; TODO: Implies that the entity can be grabbed with the Power Bracelet, or picked up/collected, depending on entity's private state?
def ENTITY_PHYSICS_SHADOW               equ $10 ; The entity casts a shadow
; Mask for all the physics flags
def ENTITY_PHYSICS_MASK                 equ $F0
; Bit numbers for wEntitiesPhysicsFlagsTable
def ENTITY_PHYSICS_B_HARMLESS           equ 7
def ENTITY_PHYSICS_B_GRABBABLE          equ 5
def ENTITY_PHYSICS_B_PROJECTILE_NOCLIP  equ 6
def ENTITY_PHYSICS_B_SHADOW             equ 4

; Values for wEntitiesTypeTable
; (See also EntityHandlersTable)
def ENTITY_ARROW                         equ $00
def ENTITY_BOOMERANG                     equ $01
def ENTITY_BOMB                          equ $02
def ENTITY_HOOKSHOT_CHAIN                equ $03
def ENTITY_MAGIC_ROD_FIREBALL            equ $04
def ENTITY_LIFTABLE_ROCK                 equ $05
def ENTITY_PUSHED_BLOCK                  equ $06 ; The entity spawned when pushing an OBJECT_PUSHABLE_BLOCK, before it's moved into its new position
def ENTITY_CHEST_WITH_ITEM               equ $07
def ENTITY_MAGIC_POWDER_SPRINKLE         equ $08
def ENTITY_OCTOROK                       equ $09
def ENTITY_OCTOROK_ROCK                  equ $0A
def ENTITY_MOBLIN                        equ $0B
def ENTITY_MOBLIN_ARROW                  equ $0C
def ENTITY_TEKTITE                       equ $0D
def ENTITY_LEEVER                        equ $0E
def ENTITY_ARMOS_STATUE                  equ $0F
def ENTITY_HIDING_GHINI                  equ $10
def ENTITY_GIANT_GHINI                   equ $11
def ENTITY_GHINI                         equ $12
def ENTITY_BROKEN_HEART_CONTAINER        equ $13 ; Killable; crashes the game if you run into it; works if you use the Magic Powder on it
def ENTITY_MOBLIN_SWORD                  equ $14
def ENTITY_ANTI_FAIRY                    equ $15
def ENTITY_SPARK_COUNTER_CLOCKWISE       equ $16
def ENTITY_SPARK_CLOCKWISE               equ $17
def ENTITY_POLS_VOICE                    equ $18
def ENTITY_KEESE                         equ $19
def ENTITY_STALFOS_AGGRESSIVE            equ $1A
def ENTITY_ZOL                           equ $1B
def ENTITY_GEL                           equ $1C
;ENTITY_DISABLED                     equ $1D
def ENTITY_STALFOS_EVASIVE               equ $1E
def ENTITY_GIBDO                         equ $1F
def ENTITY_HARDHAT_BEETLE                equ $20
def ENTITY_WIZROBE                       equ $21
def ENTITY_WIZROBE_PROJECTILE            equ $22
def ENTITY_LIKE_LIKE                     equ $23
def ENTITY_IRON_MASK                     equ $24
def ENTITY_SMALL_EXPLOSION_ENEMY         equ $25
def ENTITY_SMALL_EXPLOSION_ENEMY_2       equ $26
def ENTITY_SPIKE_TRAP                    equ $27
def ENTITY_MIMIC                         equ $28
def ENTITY_MINI_MOLDORM                  equ $29
def ENTITY_LASER                         equ $2A
def ENTITY_LASER_BEAM                    equ $2B
def ENTITY_SPIKED_BEETLE                 equ $2C
def ENTITY_DROPPABLE_HEART               equ $2D
def ENTITY_DROPPABLE_RUPEE               equ $2E
def ENTITY_DROPPABLE_FAIRY               equ $2F
def ENTITY_KEY_DROP_POINT                equ $30
def ENTITY_SWORD_SHIELD_PICKUP           equ $31
def ENTITY_IRON_MASKS_MASK               equ $32
def ENTITY_PIECE_OF_POWER                equ $33
def ENTITY_GUARDIAN_ACORN                equ $34
def ENTITY_HEART_PIECE                   equ $35
def ENTITY_HEART_CONTAINER               equ $36
def ENTITY_DROPPABLE_ARROWS              equ $37
def ENTITY_DROPPABLE_BOMBS               equ $38
def ENTITY_INSTRUMENT_OF_THE_SIRENS      equ $39
def ENTITY_SLEEPY_TOADSTOOL              equ $3A
def ENTITY_DROPPABLE_MAGIC_POWDER        equ $3B
def ENTITY_HIDING_SLIME_KEY              equ $3C
def ENTITY_DROPPABLE_SECRET_SEASHELL     equ $3D
def ENTITY_MARIN                         equ $3E
def ENTITY_TARIN                         equ $3F
def ENTITY_WITCH                         equ $40
def ENTITY_OWL_EVENT                     equ $41
def ENTITY_OWL_STATUE                    equ $42
def ENTITY_SEASHELL_MANSION_TREES        equ $43
def ENTITY_YARNA_TALKING_BONES           equ $44
def ENTITY_BOULDERS                      equ $45
def ENTITY_MOVING_BLOCK_LEFT_TOP         equ $46
def ENTITY_MOVING_BLOCK_LEFT_BOTTOM      equ $47
def ENTITY_MOVING_BLOCK_BOTTOM_LEFT      equ $48
def ENTITY_MOVING_BLOCK_BOTTOM_RIGHT     equ $49
def ENTITY_COLOR_DUNGEON_BOOK            equ $4A
def ENTITY_POT                           equ $4B
;ENTITY_DISABLED                     equ $4C
def ENTITY_SHOP_OWNER                    equ $4D
def ENTITY_4E                            equ $4E ; unknown
def ENTITY_TRENDY_GAME_OWNER             equ $4F
def ENTITY_BOO_BUDDY                     equ $50
def ENTITY_KNIGHT                        equ $51
def ENTITY_TRACTOR_DEVICE                equ $52
def ENTITY_TRACTOR_DEVICE_REVERSE        equ $53
def ENTITY_FISHERMAN_FISHING_GAME        equ $54
def ENTITY_BOUNCING_BOMBITE              equ $55
def ENTITY_TIMER_BOMBITE                 equ $56
def ENTITY_PAIRODD                       equ $57
def ENTITY_PAIRODD_PROJECTILE            equ $58
def ENTITY_MOLDORM                       equ $59
def ENTITY_FACADE                        equ $5A
def ENTITY_SLIME_EYE                     equ $5B
def ENTITY_GENIE                         equ $5C
def ENTITY_SLIME_EEL                     equ $5D
def ENTITY_GHOMA                         equ $5E
def ENTITY_MASTER_STALFOS                equ $5F
def ENTITY_DODONGO_SNAKE                 equ $60
def ENTITY_WARP                          equ $61
def ENTITY_HOT_HEAD                      equ $62
def ENTITY_EVIL_EAGLE                    equ $63
def ENTITY_SOUTH_FACE_SHRINE_DOOR        equ $64 ; unknown ; @TODO unused Eagle's Tower split-screen vfx
def ENTITY_ANGLER_FISH                   equ $65
def ENTITY_CRYSTAL_SWITCH                equ $66
def ENTITY_67                            equ $67 ; unknown
def ENTITY_HOOKSHOT_BRIDGE               equ $68
def ENTITY_MOVING_BLOCK_MOVER            equ $69
def ENTITY_RAFT_RAFT_OWNER               equ $6A
def ENTITY_TEXT_DEBUGGER                 equ $6B
def ENTITY_CUCCO                         equ $6C
def ENTITY_BOW_WOW                       equ $6D
def ENTITY_BUTTERFLY                     equ $6E
def ENTITY_DOG                           equ $6F
def ENTITY_KID_70                        equ $70
def ENTITY_KID_71                        equ $71
def ENTITY_KID_72                        equ $72
def ENTITY_KID_73                        equ $73
def ENTITY_PAPAHLS_WIFE                  equ $74
def ENTITY_GRANDMA_ULRIRA                equ $75
def ENTITY_MR_WRITE                      equ $76
def ENTITY_GRANDPA_ULRIRA                equ $77
def ENTITY_YIP_YIP                       equ $78
def ENTITY_MADAM_MEOWMEOW                equ $79
def ENTITY_CROW                          equ $7A
def ENTITY_CRAZY_TRACY                   equ $7B
def ENTITY_GIANT_GOPONGA_FLOWER          equ $7C
def ENTITY_GOPONGA_FLOWER_PROJECTILE     equ $7D
def ENTITY_GOPONGA_FLOWER                equ $7E
def ENTITY_TURTLE_ROCK_HEAD              equ $7F
def ENTITY_TELEPHONE                     equ $80
def ENTITY_ROLLING_BONES                 equ $81
def ENTITY_ROLLING_BONES_BAR             equ $82
def ENTITY_DREAM_SHRINE_BED              equ $83
def ENTITY_BIG_FAIRY                     equ $84
def ENTITY_MR_WRITES_BIRD                equ $85
def ENTITY_FLOATING_ITEM                 equ $86
def ENTITY_DESERT_LANMOLA                equ $87
def ENTITY_ARMOS_KNIGHT                  equ $88
def ENTITY_HINOX                         equ $89
def ENTITY_TILE_GLINT_SHOWN              equ $8A
def ENTITY_TILE_GLINT_HIDDEN             equ $8B
def ENTITY_8C                            equ $8C ; unknown
def ENTITY_8D                            equ $8D ; unknown
def ENTITY_CUE_BALL                      equ $8E
def ENTITY_MASKED_MIMIC_GORIYA           equ $8F
def ENTITY_THREE_OF_A_KIND               equ $90
def ENTITY_ANTI_KIRBY                    equ $91
def ENTITY_SMASHER                       equ $92
def ENTITY_MAD_BOMBER                    equ $93
def ENTITY_KANALET_BOMBABLE_WALL         equ $94
def ENTITY_RICHARD                       equ $95
def ENTITY_RICHARD_FROG                  equ $96
def ENTITY_DIVABLE_WATER                 equ $97
def ENTITY_HORSE_PIECE                   equ $98
def ENTITY_WATER_TEKTITE                 equ $99
def ENTITY_FLYING_TILES                  equ $9A
def ENTITY_HIDING_ZOL                    equ $9B
def ENTITY_STAR                          equ $9C
def ENTITY_LIFTABLE_STATUE               equ $9D
def ENTITY_FIREBALL_SHOOTER              equ $9E
def ENTITY_GOOMBA                        equ $9F
def ENTITY_PEAHAT                        equ $A0
def ENTITY_SNAKE                         equ $A1
def ENTITY_PIRANHA_PLANT                 equ $A2
def ENTITY_SIDE_VIEW_PLATFORM_HORIZONTAL equ $A3
def ENTITY_SIDE_VIEW_PLATFORM_VERTICAL   equ $A4
def ENTITY_SIDE_VIEW_PLATFORM            equ $A5
def ENTITY_SIDE_VIEW_WEIGHTS             equ $A6
def ENTITY_SMASHABLE_PILLAR              equ $A7
def ENTITY_WRECKING_BALL                 equ $A8
def ENTITY_BLOOPER                       equ $A9
def ENTITY_CHEEP_CHEEP_HORIZONTAL        equ $AA
def ENTITY_CHEEP_CHEEP_VERTICAL          equ $AB
def ENTITY_CHEEP_CHEEP_JUMPING           equ $AC
def ENTITY_KIKI_THE_MONKEY               equ $AD
def ENTITY_WINGED_OCTOROK                equ $AE
def ENTITY_TRADING_ITEM                  equ $AF
def ENTITY_PINCER                        equ $B0
def ENTITY_HOLE_FILLER                   equ $B1
def ENTITY_BEETLE_SPAWNER                equ $B2
def ENTITY_HONEYCOMB                     equ $B3
def ENTITY_TARIN_BEEKEEPER               equ $B4
def ENTITY_BEAR                          equ $B5
def ENTITY_PAPAHL                        equ $B6
def ENTITY_MERMAID                       equ $B7
def ENTITY_FISHERMAN_UNDER_BRIDGE        equ $B8
def ENTITY_BUZZ_BLOB                     equ $B9
def ENTITY_BOMBER                        equ $BA
def ENTITY_BUSH_CRAWLER                  equ $BB
def ENTITY_GRIM_CREEPER                  equ $BC
def ENTITY_VIRE                          equ $BD
def ENTITY_BLAINO                        equ $BE
def ENTITY_ZOMBIE                        equ $BF
def ENTITY_MAZE_SIGNPOST                 equ $C0
def ENTITY_MARIN_AT_THE_SHORE            equ $C1
def ENTITY_MARIN_AT_TAL_TAL_HEIGHTS      equ $C2
def ENTITY_MAMU_AND_FROGS                equ $C3
def ENTITY_WALRUS                        equ $C4
def ENTITY_URCHIN                        equ $C5
def ENTITY_SAND_CRAB                     equ $C6
def ENTITY_MANBO_AND_FISHES              equ $C7
def ENTITY_BUNNY_CALLING_MARIN           equ $C8
def ENTITY_MUSICAL_NOTE                  equ $C9
def ENTITY_MAD_BATTER                    equ $CA
def ENTITY_ZORA                          equ $CB
def ENTITY_FISH                          equ $CC
def ENTITY_BANANAS_SCHULE_SALE           equ $CD
def ENTITY_MERMAID_STATUE                equ $CE
def ENTITY_SEASHELL_MANSION              equ $CF
def ENTITY_ANIMAL_D0                     equ $D0
def ENTITY_ANIMAL_D1                     equ $D1
def ENTITY_ANIMAL_D2                     equ $D2
def ENTITY_BUNNY_D3                      equ $D3
def ENTITY_GHOST                         equ $D4
def ENTITY_ROOSTER                       equ $D5
def ENTITY_SIDE_VIEW_POT                 equ $D6
def ENTITY_THWIMP                        equ $D7
def ENTITY_THWOMP                        equ $D8
def ENTITY_THWOMP_RAMMABLE               equ $D9
def ENTITY_PODOBOO                       equ $DA
def ENTITY_GIANT_BUBBLE                  equ $DB
def ENTITY_FLYING_ROOSTER_EVENTS         equ $DC
def ENTITY_BOOK                          equ $DD
def ENTITY_EGG_SONG_EVENT                equ $DE
def ENTITY_SWORD_BEAM                    equ $DF
def ENTITY_MONKEY                        equ $E0
def ENTITY_WITCH_RAT                     equ $E1
def ENTITY_FLAME_SHOOTER                 equ $E2
def ENTITY_POKEY                         equ $E3
def ENTITY_MOBLIN_KING                   equ $E4
def ENTITY_FLOATING_ITEM_2               equ $E5
def ENTITY_FINAL_NIGHTMARE               equ $E6
def ENTITY_KANALET_CASTLE_GATE_SWITCH    equ $E7
def ENTITY_ENDING_OWL_STAIR_CLIMBING     equ $E8
def ENTITY_COLOR_SHELL_RED               equ $E9
def ENTITY_COLOR_SHELL_GREEN             equ $EA
def ENTITY_COLOR_SHELL_BLUE              equ $EB
def ENTITY_COLOR_GHOUL_RED               equ $EC
def ENTITY_COLOR_GHOUL_GREEN             equ $ED
def ENTITY_COLOR_GHOUL_BLUE              equ $EE
def ENTITY_ROTOSWITCH_RED                equ $EF
def ENTITY_ROTOSWITCH_YELLOW             equ $F0
def ENTITY_ROTOSWITCH_BLUE               equ $F1
def ENTITY_FLYING_HOPPER_BOMBS           equ $F2
def ENTITY_HOPPER                        equ $F3
def ENTITY_AVALAUNCH                     equ $F4
def ENTITY_BOUNCING_BOULDER              equ $F5
def ENTITY_COLOR_GUARDIAN_BLUE           equ $F6
def ENTITY_COLOR_GUARDIAN_RED            equ $F7
def ENTITY_GIANT_BUZZ_BLOB               equ $F8
def ENTITY_HARDHIT_BEETLE                equ $F9
def ENTITY_PHOTOGRAPHER                  equ $FA
; unused                             equ $FB
; unused                             equ $FC
; unused                             equ $FD
; unused                             equ $FE
def ENTITY_NONE                          equ $FF
