; Values for entity hitbox flags.

DEF HITFLAGS_COLLISION_BOX_NORMAL EQU $00
DEF HITFLAGS_COLLISION_BOX_SMALL EQU $01
DEF HITFLAGS_COLLISION_BOX_BIG EQU $02
DEF HITFLAGS_COLLISION_BOX_SPARK EQU $03

DEF HITFLAGS_HITBOX_ENEMY EQU $00
DEF HITFLAGS_HITBOX_BLOCK EQU $04
DEF HITFLAGS_HITBOX_BIG_ENEMY EQU $08
DEF HITFLAGS_HITBOX_UNUSED_3 EQU $0C
DEF HITFLAGS_HITBOX_SMALL_ENEMY EQU $10
DEF HITFLAGS_HITBOX_UNUSED_5 EQU $14
DEF HITFLAGS_HITBOX_NPC EQU $18
DEF HITFLAGS_HITBOX_PICKUP EQU $1C
DEF HITFLAGS_HITBOX_BAR EQU $20
DEF HITFLAGS_HITBOX_PILLAR EQU $24
DEF HITFLAGS_HITBOX_MASTER_STALFOS EQU $28
DEF HITFLAGS_HITBOX_SIDE_VIEW_PLATFORM EQU $2C
DEF HITFLAGS_HITBOX_SIFE_VIEW_WEIGHTS EQU $30
DEF HITFLAGS_HITBOX_BIG_NPC EQU $34
DEF HITFLAGS_HITBOX_FLOATING_PICKUP EQU $38
DEF HITFLAGS_HITBOX_SIFE_VIEW_POT EQU $3C

DEF HITFLAGS_IGNORE_HITS EQU $80
