; Inventory-related constants

DEF INVENTORY_SLOT_COUNT EQU $0C

; Items
DEF INVENTORY_EMPTY            EQU $00
DEF INVENTORY_SWORD            EQU $01
DEF INVENTORY_BOMBS            EQU $02
DEF INVENTORY_POWER_BRACELET   EQU $03
DEF INVENTORY_SHIELD           EQU $04
DEF INVENTORY_BOW              EQU $05
DEF INVENTORY_HOOKSHOT         EQU $06
DEF INVENTORY_MAGIC_ROD        EQU $07
DEF INVENTORY_PEGASUS_BOOTS    EQU $08
DEF INVENTORY_OCARINA          EQU $09
DEF INVENTORY_ROCS_FEATHER     EQU $0A
DEF INVENTORY_SHOVEL           EQU $0B
DEF INVENTORY_MAGIC_POWDER     EQU $0C
DEF INVENTORY_BOOMERANG        EQU $0D

; Minimaps layout
; Only $0, $11 and $30 are used in the final game
DEF INVENTORY_MINIMAP_SINGLE_FLOOR  EQU $00
DEF INVENTORY_MINIMAP_V_SPLIT_A     EQU $10
DEF INVENTORY_MINIMAP_V_SPBIT_A     EQU $11
DEF INVENTORY_MINIMAP_H_SPLIT_A     EQU $20
DEF INVENTORY_MINIMAP_H_SPLIT_B     EQU $21
DEF INVENTORY_MINIMAP_FOUR_FLOORS_A EQU $30
DEF INVENTORY_MINIMAP_FOUR_FLOORS_B EQU $31
DEF INVENTORY_MINIMAP_FOUR_FLOORS_C EQU $32
DEF INVENTORY_MINIMAP_FOUR_FLOORS_D EQU $33
