; Inventory-related constants

INVENTORY_SLOT_COUNT equ $0C

; Items
INVENTORY_SWORD           equ $01
INVENTORY_BOMBS           equ $02
INVENTORY_POWER_BRACELET  equ $03
INVENTORY_SHIELD          equ $04
INVENTORY_BOW             equ $05
INVENTORY_HOOKSHOT        equ $06
INVENTORY_MAGIC_ROD       equ $07
INVENTORY_PEGASUS_BOOTS   equ $08
INVENTORY_OCARINA         equ $09
INVENTORY_ROCS_FEATHER    equ $0A
INVENTORY_SHOVEL          equ $0B
INVENTORY_MAGIC_POWDER    equ $0C
INVENTORY_BOOMERANG       equ $0D

