;
; Constants for the physics system
;

; Values for wCollisionType:
DEF COLLISION_TYPE_NONE         EQU $00
DEF COLLISION_TYPE_UP           EQU $01
DEF COLLISION_TYPE_DOWN         EQU $02
DEF COLLISION_TYPE_VERTICAL     EQU $03
DEF COLLISION_TYPE_LEFT         EQU $04
DEF COLLISION_TYPE_RIGHT        EQU $08
DEF COLLISION_TYPE_HORIZONTAL   EQU $0C
DEF COLLISION_TYPE_UNKNOWN_10   EQU $10
