; Values for hReplaceTiles

def REPLACE_TILES_NONE              equ $00
def REPLACE_TILES_EE_RIDER_VISIBLE  equ $01
def REPLACE_TILES_EE_RIDER_HIDDEN   equ $02
def REPLACE_TILES_BUTTON_PRESSED    equ $03
def REPLACE_TILES_UNKNOWN_04        equ $04
def REPLACE_TILES_UNKNOWN_08        equ $08
def REPLACE_TILES_GOLDEN_LEAF       equ $09
def REPLACE_TILES_TOADSTOOL         equ $0A
def REPLACE_TILES_MAGIC_POWDER      equ $0B
def REPLACE_TILES_SIRENS_INSTRUMENT equ $0C
def REPLACE_TILES_TRADING_ITEM      equ $0D
def REPLACE_TILES_ISLAND_FADE       equ $0E
def REPLACE_TILES_MARIN_SITTING     equ $0F
def REPLACE_TILES_MARIN_STANDING    equ $10
