; Values for hReplaceTiles

DEF REPLACE_TILES_NONE              EQU $00
DEF REPLACE_TILES_EE_RIDER_VISIBLE  EQU $01
DEF REPLACE_TILES_EE_RIDER_HIDDEN   EQU $02
DEF REPLACE_TILES_BUTTON_PRESSED    EQU $03
DEF REPLACE_TILES_UNKNOWN_04        EQU $04
DEF REPLACE_TILES_UNKNOWN_08        EQU $08
DEF REPLACE_TILES_GOLDEN_LEAF       EQU $09
DEF REPLACE_TILES_TOADSTOOL         EQU $0A
DEF REPLACE_TILES_MAGIC_POWDER      EQU $0B
DEF REPLACE_TILES_SIRENS_INSTRUMENT EQU $0C
DEF REPLACE_TILES_TRADING_ITEM      EQU $0D
DEF REPLACE_TILES_ISLAND_FADE       EQU $0E
DEF REPLACE_TILES_MARIN_SITTING     EQU $0F
DEF REPLACE_TILES_MARIN_STANDING    EQU $10
