; Values for hReplaceTiles

REPLACE_TILES_NONE              equ $00
REPLACE_TILES_EE_RIDER_VISIBLE  equ $01
REPLACE_TILES_EE_RIDER_HIDDEN   equ $02
REPLACE_TILES_BUTTON_PRESSED    equ $03
REPLACE_TILES_UNKNOWN_04        equ $04
REPLACE_TILES_UNKNOWN_08        equ $08
REPLACE_TILES_GOLDEN_LEAF       equ $09
REPLACE_TILES_TOADSTOOL         equ $0A
REPLACE_TILES_MAGIC_POWDER      equ $0B
REPLACE_TILES_SIRENS_INSTRUMENT equ $0C
REPLACE_TILES_TRADING_ITEM      equ $0D
REPLACE_TILES_ISLAND_FADE       equ $0E
REPLACE_TILES_MARIN_SITTING     equ $0F
REPLACE_TILES_MARIN_STANDING    equ $10
