; File generated automatically by `tools/generate_map_data.py`

; Values for indoor rooms templates
DEF ROOM_TEMPLATE_TOP_RIGHT_BOTTOM_LEFT EQU $00
DEF ROOM_TEMPLATE_RIGHT_BOTTOM_LEFT     EQU $10
DEF ROOM_TEMPLATE_TOP_LEFT_BOTTOM       EQU $20
DEF ROOM_TEMPLATE_LEFT_TOP_RIGHT        EQU $30
DEF ROOM_TEMPLATE_TOP_RIGHT_BOTTOM      EQU $40
DEF ROOM_TEMPLATE_BOTTOM_LEFT           EQU $50
DEF ROOM_TEMPLATE_BOTTOM_RIGHT          EQU $60
DEF ROOM_TEMPLATE_TOP_RIGHT             EQU $70
DEF ROOM_TEMPLATE_TOP_LEFT              EQU $80
