;
; Constants for audio effects
;

; Values for hJingle
JINGLE_TREASURE_FOUND   equ $01
JINGLE_PUZZLE_SOLVED    equ $02
JINGLE_BOW_WOW_CHOMP    equ $03
JINGLE_CHARGING_SWORD   equ $04
JINGLE_POWDER           equ $05
JINGlE_ENNEMY_MORPH_IN  equ $06
JINGLE_SWORD_POKING     equ $07
JINGLE_JUMP_DOWN        equ $08
JINGLE_BUMP             equ $09
JINGLE_MOVE_SELECTION   equ $0A
JINGLE_HUGE_BUMP        equ $0B
JINGLE_REVOLVING_DOOR   equ $0C
JINGLE_FEATHER_JUMP     equ $0D
JINGLE_WATER_DIVE       equ $0E
JINGLE_OPEN_INVENTORY   equ $11
JINGLE_CLOSE_INVENTORY  equ $12
JINGLE_VALIDATE         equ $13
JINGLE_GOT_HEART        equ $14
JINGLE_DIALOG_BREAK     equ $15
JINGLE_GOT_POWER_UP     equ $17
JINGLE_ITEM_FALLING     equ $18
JINGLE_NEW_HEART        equ $19
JINGLE_WRONG_ANSWER     equ $1D
JINGLE_FOREST_LOST      equ $1E
JINGLE_ENNEMY_MORPH_OUT equ $1F
JINGLE_BIG_BUMP         equ $20
JINGLE_SEAGULL          equ $21
JINGLE_DUNGEON_OPENED   equ $23
JINGLE_JUMP             equ $24
JINGLE_INSTRUMENT_WARP  equ $2B
JINGLE_MANBO_WARP       equ $2C
JINGLE_ENNEMY_SHRIEK    equ $3C

; Values for hSfx
SFX_SWORD_A         equ $02
SFX_SPIN_ATTACK     equ $03
SFX_DOOR_UNLOCKED   equ $04
SFX_RUPEE           equ $05
SFX_FOOTSTEP        equ $07
SFX_CRISTAL_SMASHED equ $09
SFX_TYPEWRITER      equ $0F
SFX_BOSS_AGONY      equ $10
SFX_SWORD_B         equ $14
SFX_SWORD_C         equ $15
SFX_DRAW_SHIELD     equ $16
SFX_SWORD_D         equ $18
SFX_HOOT            equ $19
SFX_DOOR_RUMBLE     equ $2A
