
; Values for wTranscientVfxTypeTable
DEF TRANSCIENT_VFX_NONE           EQU $00
DEF TRANSCIENT_VFX_WATER_SPLASH   EQU $01
DEF TRANSCIENT_VFX_POOF           EQU $02
DEF TRANSCIENT_VFX_CHEST_APPEARS  EQU $03
DEF TRANSCIENT_VFX_STAIRS_APPEARS EQU $04
DEF TRANSCIENT_VFX_SWORD_POKE     EQU $05
DEF TRANSCIENT_VFX_LASER_BEAM     EQU $06
DEF TRANSCIENT_VFX_MOVING_SPARKLE EQU $07
DEF TRANSCIENT_VFX_SMOKE          EQU $08
DEF TRANSCIENT_VFX_RUMBLE         EQU $09
DEF TRANSCIENT_VFX_LAVA_SPLASH    EQU $0A
DEF TRANSCIENT_VFX_PEGASUS_DUST   EQU $0B
DEF TRANSCIENT_VFX_PEGASUS_SPLASH EQU $0C
DEF TRANSCIENT_VFX_SWORD_BEAM     EQU $0D
DEF TRANSCIENT_VFX_UNUSED_1       EQU $0E
DEF TRANSCIENT_VFX_UNUSED_2       EQU $0F
