
; Values for wTranscientVfxTypeTable
TRANSCIENT_VFX_NONE           equ $00
TRANSCIENT_VFX_WATER_SPLASH   equ $01
TRANSCIENT_VFX_POOF           equ $02
TRANSCIENT_VFX_CHEST_APPEARS  equ $03
TRANSCIENT_VFX_STAIRS_APPEARS equ $04
TRANSCIENT_VFX_SWORD_POKE     equ $05
TRANSCIENT_VFX_LASER_BEAM     equ $06
TRANSCIENT_VFX_MOVING_SPARKLE equ $07
TRANSCIENT_VFX_SMOKE          equ $08
TRANSCIENT_VFX_RUMBLE         equ $09
TRANSCIENT_VFX_LAVA_SPLASH    equ $0A
TRANSCIENT_VFX_PEGASUS_DUST   equ $0B
TRANSCIENT_VFX_PEGASUS_SPLASH equ $0C
TRANSCIENT_VFX_SWORD_BEAM     equ $0D
TRANSCIENT_VFX_UNUSED_1       equ $0E
TRANSCIENT_VFX_UNUSED_2       equ $0F

; Values for wLinkGroundVfx
GROUND_VFX_NONE          equ $00
GROUND_VFX_SHALLOW_WATER equ $05
GROUND_VFX_GRASS         equ $06
GROUND_VFX_PIT           equ $50
