NewStaffRoles::
    db "    1998 STAFF    "
    db "    SUPERVISOR    "
    db "     DIRECTOR     "
    db "  SCRIPT WRITER   "
    db "    PROGRAMMER    "
    db "CHARACTER DESIGNER"
    db "  SOUND COMPOSER  "
    db "     ART WORK     "
    db "TECHNICAL SUPPORT "
    db "  ENGLISH SCRIPT  "
    db "SPECIAL THANKS TO "

DebugStaffRoles::
    db "   DEBUG STAFF    "

OriginalStaffRoles::
    db "    1993 STAFF    "
    db " DUNGEON DESIGNER "
    db "   ILLUSTRATOR    "
    db "     PRODUCER     "
    db "EXECUTIVE PRODUCER"
    db "                  "

NewStaffPeople::
    db "                  "
    db "  TAKASHI TEZUKA  "
    db "YOSINORI TUTIYAMA "
    db " NOBUO MATSUMIYA  "
    db "    EIJI NOTO     "
    db "   KIYOSHI KODA   "
    db "SIGEHIRO KASAMATU "
    db "  MIKIO MISHIMA   "
    db "   KYOKO KIMURA   "
    db "   YUICHI OZAKI   "
    db "   KEIKO IZAWA    "
    db "   N KOGANEZAWA   "
    db "  AKIYA SAKAMOTO  "
    db " R&D2 DEBUG STAFF "
    db " SUPER MARIO CLUB "
    db "                  "
    db "                  "
    db "                  "
    db "YASUHISA YAMAMURA "
    db "  KENSUKE TANABE  "
    db " YOSHIAKI KOIZUMI "
    db "  KAZUAKI MORITA  "
    db "TAKAMITSU KUZUHARA"
    db " MASANAO ARIMOTO  "
    db "  SHIGEFUMI HINO  "
    db "  KAZUMI TOTAKA   "
    db "  MINAKO HAMANO   "
    db "  KOZUE ISHIKAWA  "
    db "  YOUICHI KOTABE  "
    db " TOSHIHIKO NAKAGO "
    db "    KOJI KONDO    "
    db " TOMOAKI KUROUME  "
    db "                  "
    db "                  "
    db "                  "
    db " SHIGERU MIYAMOTO "
    db " HIROSHI YAMAUCHI "
    db "THE  END          "
