charmap "<09>", $09
charmap "\"", $22
charmap "â", $24
charmap "à", $25
charmap "é", $2a
charmap "è", $2b
charmap "î", $2f
charmap "<hash>", $3b
charmap "ê", $3c
charmap "ù", $3d
charmap "Ç", $40
charmap "ï", $5b
charmap "û", $5c
charmap "ô", $5d
charmap "'", $5e
charmap "ç", $5f
charmap "<star>", $7c
charmap "Ó", $7d
charmap ";", $ad
charmap "<tri1>", $ae
charmap "<tri2>", $af
charmap "É", $ce
charmap "<heart>", $cf
charmap "<skull>", $dc
charmap "<link>", $dd
charmap "<marin>", $de
charmap "<yoshi>", $e0
charmap "<ribbon>", $e1
charmap "<dogfood>", $e2
charmap "<bananas>", $e3
charmap "<stick>", $e4
charmap "<honeycomb>", $e5
charmap "<pineapple>", $e6
charmap "<flower>", $e7
charmap "<broom>", $e8
charmap "<fishhook>", $e9
charmap "<bra>", $ea
charmap "<letter>", $ed
charmap "<dpad>", $ee
charmap "/", $ef
charmap "<up>", $f0
charmap "<down>", $f1
charmap "<left>", $f2
charmap "<right>", $f3
charmap "<ask>", $fe
charmap "@", $ff
