
charmap "Ç", $40
charmap "ï", $5b
charmap "û", $5c
charmap "ô", $5d
charmap "'", $5e
charmap "ç", $5f
charmap "", $60
charmap "<09>", $09
charmap "<22>", $22
charmap "#", $23
charmap "<24>", $24
charmap "<25>", $25
charmap "<26>", $26
charmap "é", $2a
charmap "è", $2b
charmap "î", $2f
charmap "<hash>", $3b
charmap "ê", $3c
charmap "ù", $3d
charmap "<7C>", $7c
charmap "<7D>", $7d
charmap "<AD>", $ad
charmap "<AE>", $ae
charmap "<AF>", $af
charmap "<CE>", $ce
charmap "<CF>", $cf
charmap "<DC>", $dc
charmap "<DD>", $dd
charmap "<DE>", $de
charmap "<E0>", $e0
charmap "<E1>", $e1
charmap "<E2>", $e2
charmap "<E3>", $e3
charmap "<E4>", $e4
charmap "<E5>", $e5
charmap "<E6>", $e6
charmap "<E7>", $e7
charmap "<E8>", $e8
charmap "<E9>", $e9
charmap "<EA>", $ea
charmap "<ED>", $ed
charmap "<EE>", $ee
charmap "<EF>", $ef
charmap "<F0>", $f0
charmap "<F1>", $f1
charmap "<F2>", $f2
charmap "<F3>", $f3
charmap "<ask>", $fe
charmap "@", $ff
