;
; Mapping from Unicode to the codepoints used by the ROM.
;
PUSHC
NEWCHARMAP DialogCharmap

charmap "あ", $00
charmap "い", $01
charmap "う", $02
charmap "え", $03
charmap "お", $04
charmap "か", $05
charmap "き", $06
charmap "く", $07
charmap "け", $08
charmap "こ", $09
charmap "さ", $0a
charmap "し", $0b
charmap "す", $0c
charmap "せ", $0d
charmap "そ", $0e
charmap "た", $0f
charmap "ち", $10
charmap "つ", $11
charmap "て", $12
charmap "と", $13
charmap "な", $14
charmap "に", $15
charmap "ぬ", $16
charmap "ね", $17
charmap "の", $18
charmap "は", $19
charmap "ひ", $1a
charmap "ふ", $1b
charmap "へ", $1c
charmap "ほ", $1d
charmap "ま", $1e
charmap "み", $1f
charmap "む", $20
charmap "め", $21
charmap "も", $22
charmap "や", $23
charmap "ゆ", $24
charmap "よ", $25
charmap "ら", $26
charmap "り", $27
charmap "る", $28
charmap "れ", $29
charmap "ろ", $2a
charmap "わ", $2b
charmap "を", $2c
charmap "ん", $2d
charmap "が", $2e
charmap "ぎ", $2f
charmap "ぐ", $30
charmap "げ", $31
charmap "ご", $32
charmap "ざ", $33
charmap "じ", $34
charmap "ず", $35
charmap "ぜ", $36
charmap "ぞ", $37
charmap "だ", $38
charmap "ぢ", $39
charmap "づ", $3a
charmap "で", $3b
charmap "ど", $3c
charmap "ば", $3d
charmap "び", $3e
charmap "ぶ", $3f
charmap "べ", $40
charmap "ぼ", $41
charmap "ぱ", $42
charmap "ぴ", $43
charmap "ぷ", $44
charmap "ぺ", $45
charmap "ぽ", $46
charmap "ゃ", $47
charmap "ゅ", $48
charmap "ょ", $49
charmap "っ", $4a
charmap "ア", $50
charmap "イ", $51
charmap "ウ", $52
charmap "エ", $53
charmap "オ", $54
charmap "カ", $55
charmap "キ", $56
charmap "ク", $57
charmap "ケ", $58
charmap "コ", $59
charmap "サ", $5a
charmap "シ", $5b
charmap "ス", $5c
charmap "セ", $5d
charmap "ソ", $5e
charmap "タ", $5f
charmap "チ", $60
charmap "ツ", $61
charmap "テ", $62
charmap "ト", $63
charmap "ナ", $64
charmap "ニ", $65
charmap "ヌ", $66
charmap "ネ", $67
charmap "ノ", $68
charmap "ハ", $69
charmap "ヒ", $6a
charmap "フ", $6b
charmap "ヘ", $6c
charmap "ホ", $6d
charmap "マ", $6e
charmap "ミ", $6f
charmap "ム", $70
charmap "メ", $71
charmap "モ", $72
charmap "ヤ", $73
charmap "ユ", $74
charmap "ヨ", $75
charmap "ラ", $76
charmap "リ", $77
charmap "ル", $78
charmap "レ", $79
charmap "ロ", $7a
charmap "ワ", $7b
charmap "ヲ", $7c
charmap "ン", $7d
charmap "ガ", $7e
charmap "ギ", $7f
charmap "グ", $80
charmap "ゲ", $81
charmap "ゴ", $82
charmap "ザ", $83
charmap "ジ", $84
charmap "ズ", $85
charmap "ゼ", $86
charmap "ゾ", $87
charmap "ダ", $88
charmap "ヂ", $89
charmap "ヅ", $8a
charmap "デ", $8b
charmap "ド", $8c
charmap "バ", $8d
charmap "ビ", $8e
charmap "ブ", $8f
charmap "ベ", $90
charmap "ボ", $91
charmap "パ", $92
charmap "ピ", $93
charmap "プ", $94
charmap "ペ", $95
charmap "ポ", $96
charmap "ャ", $97
charmap "ュ", $98
charmap "ョ", $99
charmap "ッ", $9a
charmap "！", $a0
charmap "？", $a1
charmap "－", $a2
charmap "　", $a3
charmap " ", $a3
charmap "．", $a4
charmap "、", $a5
charmap "。", $a6
charmap "「", $a7
charmap "」", $a8
charmap "０", $b0
charmap "１", $b1
charmap "２", $b2
charmap "３", $b3
charmap "４", $b4
charmap "５", $b5
charmap "６", $b6
charmap "７", $b7
charmap "８", $b8
charmap "９", $b9
charmap "ァ", $ba
charmap "ィ", $bb
charmap "ゥ", $bc
charmap "ェ", $bd
charmap "ォ", $be
charmap "Ｒ", $bf
charmap "#", $c0
charmap "Ａ", $d0
charmap "Ｂ", $d1
charmap "Ｃ", $d2
charmap "Ｄ", $d3
charmap "Ｅ", $d4
charmap "Ｆ", $d5
charmap "<dpad>", $d6
charmap "<letter>", $d7
charmap "<yoshi>", $d8
charmap "<flower>", $d9
charmap "<footprint>", $da
charmap "Ｘ", $db
charmap "<skull>", $dc
charmap "<link>", $dd
charmap "<marin>", $de
charmap "<tarin>", $df
charmap "<yoshi2>", $e0
charmap "<ribbon>", $e1
charmap "<dogfood>", $e2
charmap "<bananas>", $e3
charmap "<stick>", $e4
charmap "<honeycomb>", $e5
charmap "<pineapple>", $e6
charmap "<flower2>", $e7
charmap "<broom>", $e8
charmap "<fishhook>", $e9
charmap "<bra>", $ea
charmap "<scale>", $eb
charmap "<glass>", $ec
charmap "<letter2>", $ed
charmap "<dpad2>", $ee
charmap "<up>", $f0
charmap "<down>", $f1
charmap "<left>", $f2
charmap "<right>", $f3
charmap "<space>", $fd
charmap "<ask>", $fe
charmap "@", $ff

POPC
