TILES_PER_ROW equ $0B
TILES_PER_MAP equ $80

; Possible values for WR1_GameplayType
GAMEPLAY_INTRO       equ $00
GAMEPLAY_FILE_SELECT equ $02
GAMEPLAY_FILE_NEW    equ $03
GAMEPLAY_FILE_DELETE equ $04
GAMEPLAY_MINI_MAP    equ $07
GAMEPLAY_OVERWORLD   equ $0B
GAMEPLAY_INVENTORY   equ $0C
